In [2]:
import numpy as np
import torch

from mik_tools.kinematic_tools import exponential_map, log_map, skew_matrix_to_vector, vector_to_skew_matrix

In [13]:
omega = np.array([0., 0., np.pi*0.25])
omega_skew = vector_to_skew_matrix(omega)
omega_skew

array([[ 0.        , -0.78539816,  0.        ],
       [ 0.78539816,  0.        , -0.        ],
       [-0.        ,  0.        ,  0.        ]])

In [12]:
R = exponential_map(omega_skew)
R

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ],
       [ 0.        ,  0.        ,  1.        ]])

In [14]:
R_t = torch.tensor(R)

In [15]:
omega_skew_r = log_map(R)
omega_skew_r

array([[-2.84558859e-16, -7.85398163e-01,  0.00000000e+00],
       [ 7.85398163e-01, -4.85080479e-17,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00]])

In [16]:
log_map(R_t)

tensor([[ 0.0000, -0.7854,  0.0000],
        [ 0.7854,  0.0000,  0.0000],
        [ 0.0000,  0.0000,  0.0000]], dtype=torch.float64)